/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PoolResultsRouteImport } from './routes/pool-results'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PoolsIndexRouteImport } from './routes/pools/index'
import { Route as PoolsPoolIdRouteImport } from './routes/pools/$poolId'
import { Route as PoolResultsPoolIdRouteImport } from './routes/pool-results/$poolId'

const PoolResultsRoute = PoolResultsRouteImport.update({
  id: '/pool-results',
  path: '/pool-results',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolsIndexRoute = PoolsIndexRouteImport.update({
  id: '/pools/',
  path: '/pools/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolsPoolIdRoute = PoolsPoolIdRouteImport.update({
  id: '/pools/$poolId',
  path: '/pools/$poolId',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolResultsPoolIdRoute = PoolResultsPoolIdRouteImport.update({
  id: '/$poolId',
  path: '/$poolId',
  getParentRoute: () => PoolResultsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pool-results': typeof PoolResultsRouteWithChildren
  '/pool-results/$poolId': typeof PoolResultsPoolIdRoute
  '/pools/$poolId': typeof PoolsPoolIdRoute
  '/pools/': typeof PoolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pool-results': typeof PoolResultsRouteWithChildren
  '/pool-results/$poolId': typeof PoolResultsPoolIdRoute
  '/pools/$poolId': typeof PoolsPoolIdRoute
  '/pools': typeof PoolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pool-results': typeof PoolResultsRouteWithChildren
  '/pool-results/$poolId': typeof PoolResultsPoolIdRoute
  '/pools/$poolId': typeof PoolsPoolIdRoute
  '/pools/': typeof PoolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pool-results'
    | '/pool-results/$poolId'
    | '/pools/$poolId'
    | '/pools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pool-results'
    | '/pool-results/$poolId'
    | '/pools/$poolId'
    | '/pools'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/pool-results'
    | '/pool-results/$poolId'
    | '/pools/$poolId'
    | '/pools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PoolResultsRoute: typeof PoolResultsRouteWithChildren
  PoolsPoolIdRoute: typeof PoolsPoolIdRoute
  PoolsIndexRoute: typeof PoolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pool-results': {
      id: '/pool-results'
      path: '/pool-results'
      fullPath: '/pool-results'
      preLoaderRoute: typeof PoolResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pools/': {
      id: '/pools/'
      path: '/pools'
      fullPath: '/pools/'
      preLoaderRoute: typeof PoolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pools/$poolId': {
      id: '/pools/$poolId'
      path: '/pools/$poolId'
      fullPath: '/pools/$poolId'
      preLoaderRoute: typeof PoolsPoolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pool-results/$poolId': {
      id: '/pool-results/$poolId'
      path: '/$poolId'
      fullPath: '/pool-results/$poolId'
      preLoaderRoute: typeof PoolResultsPoolIdRouteImport
      parentRoute: typeof PoolResultsRoute
    }
  }
}

interface PoolResultsRouteChildren {
  PoolResultsPoolIdRoute: typeof PoolResultsPoolIdRoute
}

const PoolResultsRouteChildren: PoolResultsRouteChildren = {
  PoolResultsPoolIdRoute: PoolResultsPoolIdRoute,
}

const PoolResultsRouteWithChildren = PoolResultsRoute._addFileChildren(
  PoolResultsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PoolResultsRoute: PoolResultsRouteWithChildren,
  PoolsPoolIdRoute: PoolsPoolIdRoute,
  PoolsIndexRoute: PoolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
